name: 'HRBB OA SIGN'

on:
  watch:
    types: started
  push:
  schedule:
    - cron: '5 0,10 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v1
        - name: 'Set up Python'
          uses: actions/setup-python@v1
          with:
            python-version: '3.8'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Setup timezone
          uses: zcong1993/setup-timezone@v1.1.2
          with:
            timezone: 'Asia/Shanghai'
        - name: 'Sign'
          env:
            EMPLID: ${{ secrets.EMPLID }}
            PASSWD: ${{ secrets.PASSWD }}
          run: python oa_sign.py
        - name: 'Send mail'
          uses: dawidd6/action-send-mail@master
          with:
            server_address: smtp.qq.com
            server_port: 465
            secure: true
            username: ${{ secrets.MAIL_USERNAME }}
            password: ${{ secrets.MAIL_PASSWORD }}
            subject: 签到结果
            body: file://oa_sign.log
            to: ${{ secrets.MAIL_TO }}
            from: GitHub Actions
            content_type: text/html
